version: '3.9'

services:
  frontend:
    image: front-image
    container_name: luxe_frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - luxe-network

  backend:
    image: backend-image
    container_name: luxe_backend
    ports:
      - "5000:5000"
    environment:
      # Example environment variables
      APP_ENV: development
    networks:
      - luxe-network

networks:
  luxe-network:
    driver: bridge
