version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9999:5000"  # Changed to high port
    environment:
      FLASK_ENV: development
      DEBUG: 1
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "8888:80"  # Changed to high port
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
