version: '3.8'

services:
  backend:
    environment:
      - FLASK_ENV=development
      - DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/__pycache__

  frontend:
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=development
