version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: infra/Dockerfile.app
    container_name: backend
    ports:
      - "5000:8000"
    environment:
      - ENV=dev

  front:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: front
    ports:
      - "8081:80"
