version: '3.8'

services:
  backend:
    image: ${DOCKER_REGISTRY}/luxe-jewelry-store-backend:${DOCKER_TAG}
    environment:
      - FLASK_ENV=production
      - DEBUG=0
    ports:
      - "5000:5000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ${DOCKER_REGISTRY}/luxe-jewelry-store-frontend:${DOCKER_TAG}
    ports:
      - "80:80"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
