version: "3.9"

services:
  backend:
    build:
      context: ./backend              # points to backend folder
      dockerfile: infra/Dockerfile.app  # points to infra/Dockerfile.app
    container_name: backend
    ports:
      - "5000:8000"  # host:container (backend runs on 8000 inside container)

  front:
    build:
      context: ./frontend             # points to frontend folder
      dockerfile: ../backend/infra/Dockerfile.nginx  # use nginx Dockerfile from infra
    container_name: front
    ports:
      - "8081:80"   # host:container (nginx runs on port 80 inside container)


