version: '3.8'

# Define common environment variables for all services
x-common-env: &common-environment
  TZ: "${TZ:-UTC}"
  PYTHONUNBUFFERED: 1
  PYTHONDONTWRITEBYTECODE: 1

# Common build arguments
x-build-args: &build-args
  BUILDKIT_INLINE_CACHE: 1

# Common healthcheck configuration
x-healthcheck: &healthcheck
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 5s

services:
  backend:
    build:
      context: ./backend
      target: builder
      args:
        <<: *build-args
    image: ${DOCKER_REGISTRY:-israelatia}/luxe-jewelry-store-backend:${TAG:-latest}
    container_name: luxe-backend
    restart: unless-stopped
    environment:
      <<: *common-environment
      FLASK_APP: main.py
      FLASK_ENV: ${FLASK_ENV:-production}
      DEBUG: ${DEBUG:-0}
      PORT: 5000
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    volumes:
      - backend-data:/app/data
      - ./backend:/app:ro
      - /app/__pycache__
    networks:
      - luxe-network
    <<: *healthcheck
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  frontend:
    build:
      context: ./frontend
      target: builder
      args:
        <<: *build-args
    image: ${DOCKER_REGISTRY:-israelatia}/luxe-jewelry-store-frontend:${TAG:-latest}
    container_name: luxe-frontend
    restart: unless-stopped
    environment:
      <<: *common-environment
      NODE_ENV: ${NODE_ENV:-production}
      VITE_API_URL: ${VITE_API_URL:-http://backend:5000}
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    volumes:
      - frontend-data:/usr/share/nginx/html
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - luxe-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  luxe-network:
    driver: bridge

volumes:
  backend-data:
  frontend-data:
