version: '3.8'

networks:
  luxe-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: luxe_backend
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      PYTHONUNBUFFERED: 1
    restart: unless-stopped
    networks:
      - luxe-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: luxe_frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - luxe-network
