apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "LuxeAppSecrets"
        objectType: "secretsmanager"
