# infra/Dockerfile.nginx
FROM nginx:latest

# Copy frontend static files
COPY frontend/ /usr/share/nginx/html/

# Optional: custom nginx config
# COPY infra/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

