apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: demo-app
type: Opaque
data:
  # Example: echo -n 'your-secret-key' | base64
  SECRET_KEY: eW91ci1zZWNyZXQta2V5Cg==
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAZGI6NTQzMi9kYg==