apiVersion: v1
kind: Service
metadata:
  name: {{ include "luxe-jewelry-store.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "luxe-jewelry-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "luxe-jewelry-store.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
