# Default values for luxe-jewelry-store.

# Global settings
namespace: demo-app

# Backend configuration
backend:
  image:
    repository: israelatia/luxe-jewelry-store-backend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2
  service:
    type: ClusterIP
    port: 80
    targetPort: 5000
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  livenessProbe:
    path: /health
    port: 5000
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    path: /health
    port: 5000
    initialDelaySeconds: 5
    periodSeconds: 5
  env:
    FLASK_APP: "main.py"
    FLASK_ENV: "production"
    DEBUG: "0"
    PORT: "5000"

# Frontend configuration
frontend:
  image:
    repository: israelatia/luxe-jewelry-store-frontend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  livenessProbe:
    path: /
    port: 80
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    path: /
    port: 80
    initialDelaySeconds: 5
    periodSeconds: 5
  env:
    NODE_ENV: "production"
    VITE_API_URL: "http://luxe-backend.demo-app.svc.cluster.local"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: luxe-jewelry.local
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix

# Persistence configuration
persistence:
  backend:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce
  frontend:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce

# Autoscaling configuration
autoscaling:
  enabled: true
  backend:
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
  frontend:
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
